spring:
  application:
    name: order-query-service
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://config-service:8888
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"

