server:
  port: 9900
spring:
  application:
    name: order-query-service
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
aws:
  dynamodb:
    endpoint: "http://localhost:8000"
